<!DOCTYPE HTML>
<html>
<head>
    <title> 后台管理系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="public/bui/assets/css/dpl-min.css" rel="stylesheet" type="text/css" />
    <link href="public/bui/assets/css/bui-min.css" rel="stylesheet" type="text/css" />
    <link href="public/bui/assets/css/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="header">
    <div class="dl-title"><span class="">后台管理系统</span></div>
    <div class="dl-log">欢迎您，<span class="dl-log-user">XXX</span>
        <a href="###" title="退出系统" class="dl-log-quit">[退出]</a>
    </div>
</div>
<div class="content">
    <div class="dl-main-nav">
        <ul id="J_Nav"  class="nav-list ks-clear">
            <li class="nav-item dl-selected"><div class="nav-item-inner nav-storage">主菜单</div></li>
            <!-- <li class="nav-item"><div class="nav-item-inner nav-inventory">搜索页</div></li> -->
        </ul>
    </div>
    <ul id="J_NavContent" class="dl-tab-conten">

    </ul>

</div>
<script type="text/javascript" src="public/bui/assets/js/jquery-1.8.1.min.js"></script>
<script type="text/javascript" src="public/bui/assets/js/bui-min.js"></script>
<script type="text/javascript" src="public/bui/assets/js/config-min.js"></script>
<script>
    BUI.use('common/main',function(){
        var config = [{
            id:'menu',
            homePage : 'main-menu',
            menu:[{
                text:'主菜单',
                items:[
                    {id:'main-menu',text:'欢迎页面',href:'admin/welcome', closeable : false}
                ]
            },{
                text:'分类管理',
                items:[
                    {id:'cate_index',text:'分类列表',href:''},
                    {id:'cate_add',text:'添加分类',href:''}
                ]
            }]
        },{
            id:'search',
            menu:[{
                text:'搜索页面',
                items:[
                    {id:'introduce',text:'搜索页面简介',href:'search/introduce.html'}
                ]
            }]
        }];
        new PageUtil.MainPage({
            modulesConfig : config
        });
    });

</script>
</body>
</html>