<!DOCTYPE HTML>
<html>
<head>
    <title> 首页代码结构</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/public/bui/assets/css/dpl-min.css" rel="stylesheet" type="text/css" />
    <link href="/public/bui/assets/css/bui-min.css" rel="stylesheet" type="text/css" />
    <link href="/public/bui/assets/css/page-min.css" rel="stylesheet" type="text/css" />
</head>
<body>


<div class="container">
    <!-- 前端框架　<small>轻松开发，专注您的业务！</small> -->

    <div class="alert alert-success" role="alert" style="margin:0 0 5px; padding:5px 15px;">
        <!-- <strong>欢迎你!</strong> -->
        <br><span>开发：</span> <a href="javascript:;">admin</a>
        <br><span>测试 & 推广：</span> <a href="javascript:;">admin</a>
        <br><span>测试 & 试用：</span> <a href="javascript:;">admin</a>
    </div>

    <div class="col-md-6" style="padding:5px;">
        <div class="alert alert-info" role="alert" style="margin:0 0 5px; padding:5px 15px;">
            <h5>项目地址：<a href="javascript:;" target="_blank">GIT</a>　<a href="javascript:;" target="_blank">OSCHINA</a></h5>
            <h5>微博地址：<a href="javascript:;" target="_blank">a</a></h5>
            <h5>PHP整合：<a href="javascript:;" target="_blank">b</a></h5>
            <h5>JAVA整合：<a href="javascript:;" target="_blank">c</a></h5>
        </div>
    </div>
</div>
<script type="text/javascript" src="/public/bui/assets/js/jquery-1.8.1.min.js"></script>
<script type="text/javascript" src="/public/bui/assets/js/bui-min.js"></script>
<script type="text/javascript" src="/public/bui/assets/js/config-min.js"></script>

<body>
</html>